SELECT JSON_OBJECT(

    'EMPLEADO' VALUE FIRST_NAME,
    'EMAIL' VALUE EMAIL,
    'SALARIO' VALUE SALARY

) AS "DATOS" FROM EMPLOYEES;

SELECT JSON_OBJECT(
    'NOMBRE DEPARTAMENTO' VALUE DEPARTMENT_NAME,
    'MANAGER' VALUE MANAGER_ID ABSENT ON NULL
) AS "DATOS" FROM DEPARTMENTS;


SELECT JSON_OBJECTAGG(

    COUNTRY_ID VALUE COUNTRY_NAME

) FROM COUNTRIES;


CREATE TABLE EQUIPO(

    ID_EQUIPO VARCHAR2(2) NOT NULL PRIMARY KEY,
    DATOS_EQUIPO BLOB NOT NULL
);

ALTER TABLE EQUIPO
ADD CONSTRAINT COLUMNA_JSON 
CHECK (DATOS_EQUIPO IS JSON);


INSERT INTO EQUIPO (ID_EQUIPO,DATOS_EQUIPO) VALUES (

    'CR',
    UTL_RAW.CAST_TO_RAW(
    
        '{
            "JUGADORES" : [
            
                {
                    "NOMBRE" : "MARCEL LOPEZ",
                    "POSICION" : "PORTERO"
                },
                
                {
                    "NOMBRE" : "MARCO PEREZ",
                    "POSICION" : "DEFENSA"
                }   
            ]
        }' 
    )
);



SELECT * FROM EQUIPO;



SELECT JSON_SERIALIZE(  DATOS_EQUIPO RETURNING VARCHAR2 PRETTY ) FROM EQUIPO;



SELECT JSON_QUERY( DATOS_EQUIPO, '$.JUGADORES[1]' RETURNING VARCHAR2 PRETTY WITH WRAPPER ) FROM EQUIPO;



